// Types for QDRANT matching system

export interface ClubProfile {
  id: string;
  metadata: {
    // Basic information
    name: string;
    city: string;
    country: string;
    division: string;
    divisionLevel: number; // 1 = Pro, 2 = Semi-pro, 3 = National, 4 = Regional
    
    // Recruitment
    recruitmentNeeds: {
      positions: string[]; // ["striker", "midfielder", "defender", "goalkeeper"]
      priorityLevel: "urgent" | "important" | "flexible";
      targetAge: { min: number; max: number };
      experienceLevel: "amateur" | "semi-pro" | "professional";
    };
    
    // Budget & Conditions
    budget: {
      min: number; // Monthly salary minimum (€)
      max: number; // Monthly salary maximum (€)
      bonuses: boolean; // Performance bonuses
      housing: boolean; // Housing provided
      insurance: boolean; // Health insurance
    };
    
    // Infrastructure & Style
    facilities: string[]; // ["synthetic_field", "gym", "video_analysis", "physio"]
    playingStyle: string[]; // ["possession", "counter_attack", "pressing", "defensive"]
    teamCulture: string[]; // ["competitive", "family", "professional", "youth_development"]
    
    // Club statistics
    stats: {
      squadSize: number;
      averageAge: number;
      matchesPerSeason: number;
      trainingSessionsPerWeek: number;
    };
    
    // Location
    location: {
      latitude: number;
      longitude: number;
      nearbyCity: string;
    };
    
    // Dates
    createdAt: string;
    updatedAt: string;
    activeRecruitment: boolean;
  };
  
  // Embedding vector (generated by AI)
  vector: number[]; // Dimension 1536 (OpenAI) or 768 (Sentence-Transformers)
}

export interface PlayerProfile {
  id: string;
  metadata: {
    // Personal information
    name: string;
    age: number;
    nationality: string;
    city: string;
    birthDate?: string;
    
    // Sport profile
    position: string; // "striker", "midfielder", "defender", "goalkeeper"
    secondaryPositions: string[];
    strongFoot: "left" | "right" | "both";
    level: "amateur" | "semi-pro" | "professional";
    experienceYears: number;
    
    // Statistics
    stats: {
      goals: number;
      assists: number;
      matches: number;
      minutesPlayed: number;
      yellowCards: number;
      redCards: number;
    };
    
    // Career preferences
    careerGoals: {
      desiredDivision: string[]; // ["National 2", "National 3", "Regional 1"]
      salaryExpectation: { min: number; max: number };
      willingToRelocate: boolean;
      maxDistanceKm: number; // Max distance from their city
      contractDuration: "short" | "medium" | "long"; // 6 months, 1-2 years, 2+ years
    };
    
    // Skills & Style
    strengths: string[]; // ["speed", "technique", "vision", "heading", "shooting"]
    playingStyle: string[]; // ["aggressive", "technical", "tactical", "physical"]
    personality: string[]; // ["leader", "team_player", "competitive", "calm"]
    
    // Availability
    availability: {
      immediate: boolean;
      startDate: string;
      commitmentLevel: "full_time" | "part_time";
    };
    
    // Media
    highlightVideoUrl?: string;
    avatarUrl?: string;
    
    // Dates
    createdAt: string;
    updatedAt: string;
  };
  
  // Embedding vector
  vector: number[]; // Same dimension as clubs
}

export interface MatchScore {
  totalScore: number; // 0-100
  breakdown: {
    positionMatch: number; // 0-25
    levelMatch: number; // 0-25
    budgetMatch: number; // 0-20
    locationMatch: number; // 0-15
    styleMatch: number; // 0-15
  };
  reasoning: string[];
}
